import { NestFactory } from '@nestjs/core';
import { Logger } from '@nestjs/common';
import { AppModule } from '../app.module';
import { EslasticService } from '../eslastic/eslastic.service';
import { MoviesService } from '../movies/movies.service';
import { moviesMock } from './movies.mock';

async function seed() {
  const logger = new Logger('Seed');
  const app = await NestFactory.createApplicationContext(AppModule);
  const eslasticService = app.get(EslasticService);
  const moviesService = app.get(MoviesService);

  // Delete and recreate the movies index to ensure fresh mapping with suggest field
  const indexExists = await eslasticService.indexExists(MoviesService.INDEX);
  if (indexExists) {
    await eslasticService.deleteIndex(MoviesService.INDEX);
    logger.log(`Index '${MoviesService.INDEX}' deleted`);
  }

  await eslasticService.createIndex(MoviesService.INDEX, undefined, {
    properties: {
      name: { type: 'text' },
      title: { type: 'text' },
      description: { type: 'text' },
      suggest: { type: 'completion' },
    },
  });
  logger.log(`Index '${MoviesService.INDEX}' created`);

  // Seed all movies (suggest field is auto-generated by the service)
  for (const movie of moviesMock) {
    await moviesService.createMovie(movie);
  }

  logger.log(`Successfully seeded ${moviesMock.length} movies`);

  await app.close();
}

void seed();
